package View;

import Control.ControlFuncionario;
import java.io.File;
import java.util.Formatter;
import javax.swing.JOptionPane;
/**
 *
 * @author Daniel Lacerda
 * @author João Victor Moura
 */
public class TelaCadastroProfessor extends javax.swing.JInternalFrame {

    String barra = File.separator;
    String local = System.getProperty("user.dir") + barra + "Dados_Professor"+barra;
    
    /**
     * Creates new form Professor
     */
    public TelaCadastroProfessor() {
        initComponents();
    }

    public void CriarArquivo(){
        String arquivo = tfCodigoPro.getText()+".txt";
        File criar_local = new File(local);
        File criar_arquivo = new File(local+arquivo);
       
        
         if(tfCodigoPro.getText().equals(null)||tfNomePro.getText().equals(null)||tfCodigoPro.getText().equals("")
           || tfNomePro.getText().equals("")|| tfSalarioPro.getText().equals("") || tfSalarioPro.getText().equals(null)){ 
            JOptionPane.showMessageDialog(null, "Dados inválidos ou em Branco, por favor, tente novamente.");
         }else{
        try {
           
        if(criar_arquivo.exists()){
            JOptionPane.showMessageDialog(rootPane, "Já existe um Registro de Professor com esse Codigo: " +tfCodigoPro.getText());
        }else
            {
                criar_local.mkdirs();
                Formatter criar = new Formatter(local+arquivo);
                               
                criar.format("%s\r\n %s\r\n %s\r\n %s\r\n ","_______DADOS DO FUNCIONARIO______"
                ,"Codigo: "+tfCodigoPro.getText()
                ,"Nome: "+tfNomePro.getText()
                ,"Salario: "+tfSalarioPro.getText());
                   
                criar.close();
                JOptionPane.showMessageDialog(null, "Funcionario(a) Cadastrado{a):"+
                "\n  -Codigo:" +tfCodigoPro.getText()+
                "\n  -Nome: "+tfNomePro.getText() +
                "\n  -Salário:"+tfSalarioPro.getText());
              
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Não foi Possivel Cadastrar");
        }
    }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigoPro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNomePro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfSalarioPro = new javax.swing.JTextField();
        salarioprof = new javax.swing.JSlider();

        setTitle("Cadastro Professor");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Salario:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfSalarioPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSalarioPro.setToolTipText("");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, salarioprof, org.jdesktop.beansbinding.ELProperty.create("${value}"), tfSalarioPro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        tfSalarioPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalarioProActionPerformed(evt);
            }
        });

        salarioprof.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salarioprof.setMaximum(15000);
        salarioprof.setValue(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(salarioprof, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tfCodigoPro, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(tfSalarioPro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomePro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfNomePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(salarioprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfSalarioPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cargo = "Professor";
        CriarArquivo();
        ControlFuncionario.Addfuncionario(tfCodigoPro.getText(), cargo ,tfNomePro.getText(), tfSalarioPro.getText());
        //ZERAR CAMPOS
        tfCodigoPro.setText("");
        tfNomePro.setText("");
        tfSalarioPro.setText("");
        
        
        tfCodigoPro.requestFocus();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfSalarioProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalarioProActionPerformed
        tfSalarioPro.getText().equals(salarioprof.getValue());
    }//GEN-LAST:event_tfSalarioProActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider salarioprof;
    private javax.swing.JTextField tfCodigoPro;
    private javax.swing.JTextField tfNomePro;
    private javax.swing.JTextField tfSalarioPro;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
